### ISSUE TITLE
Search text box is buggy on FF

### ISSUE THREAD

**Issue by edimitchel** [Akryum/awesomejs.dev#1] opened 2019-10-11 14:02 UTC
Hi !

I found an issue with my **Firefox ESR 60**.
The search box is not available (even with focus). Search component seems to not be render properly.

![5c25f803-651d-4fcd-9470-40232516fd94](https://user-images.githubusercontent.com/2922851/66657519-3ef7cc80-ec40-11e9-9481-a983ec8e1e89.gif)

DOM of the header

```html
<div class="flex px-4 my-4 lg:px-16 lg:my-8 relative">
  <a href="/" class="flex-none router-link-active"
    ><img src="/img/project-types/vue.png" alt="Logo" class="w-8 h-8 rounded"
  /></a>
  <div class="flex-1"></div>
  <a
    href="/pkg/add?projectTypeId=244960085436006912"
    class="inline-block cursor-pointer text-center relative rounded select-none outline-none px-4 py-1 text-gray-600 hover:text-gray-500 mr-4"
    type="button"
    tabindex="0"
    role="button"
    ><div class="flex items-center justify-center rounded">
      <i class="material-icons text-lg mr-2">add</i> Add package
      <!---->
    </div>
    <!----></a
  >
  <div>
    <div class="w-8 h-8 flex items-center justify-center">
      <a href="/me/" class=""
        ><img
          src="https://avatars3.githubusercontent.com/u/2922851?v=4"
          alt="User"
          class="max-w-full max-h-full rounded-full bg-gray-700"
      /></a>
    </div>
  </div>
  <div class="absolute top-0 left-0 w-full h-0 flex justify-center">
    <button
      type="button"
      tabindex="0"
      role="button"
      class="inline-block cursor-pointer text-center relative rounded select-none outline-none px-4 py-1 text-gray-600 hover:text-gray-500"
    >
      <div class="flex items-center justify-center rounded">
        <i class="material-icons text-lg mr-2">search</i> Search...
        <!---->
      </div>
      <!---->
    </button>
  </div>
</div>
```

**Comment by Akryum** [comment] 2019-10-11 15:14
This seems to be a bug fixed in more recent releases of Fx. I can't reproduce on mine (v.69).

**Comment by edimitchel** [comment] 2019-10-11 18:27
Yes, but ESR version is blocked to 60th version.

**Closed as completed** 2019-12-17 11:48 UTC
Labels: bug
